lidar_2/neo_sick_s300_node:
  ros__parameters:
    port: /dev/neo-s300-2
    baud: 500000
    scan_cycle_time: 0.040
    scan_duration: 0.025
    scan_delay: 0.045
    frame_id: lidar_2_link
    scan_intervals: [[-2.4, 2.4]] #[rad] these intervals are included to the scan +-95Â°

